# Generated by Django 2.2.6 on 2019-10-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
