# Generated by Django 2.2.3 on 2019-09-05 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_class_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('linked_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class')),
            ],
        ),
    ]
