# Generated by Django 2.2.3 on 2019-09-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_user'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Assignment',
        ),
    ]
