# Generated by Django 2.2.3 on 2019-09-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='status',
            new_name='done',
        ),
    ]
