# Generated by Django 2.2.5 on 2020-02-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_auto_20200227_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_assignment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='model_assignment',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
