# Generated by Django 3.0.6 on 2020-06-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_assignment_linked_class_linker'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submission',
            field=models.TextField(default=''),
        ),
    ]
