# Generated by Django 3.0.7 on 2020-06-09 04:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpwd',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=300, unique=True),
        ),
    ]
